[package]
name = "mirai_rs_mock"
version = "0.0.1"
edition = "2018"

[dependencies]
mirai_rs = { path = "../mirai_rs" }
mirai_test = { path = "../mirai_test" }
actix-web = "2"
actix-rt = "1"
serde_json = "1.0"